backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

corner-radius = 12;
frame-opacity = 1.0;

blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

rules = (
  {
    match = "window_type = 'tooltip'";
    fade = false;
    shadow = true;
    opacity = 0.75;
    full-shadow = false;
  },
  {
    match = "name = 'Notification' || class_g = 'Conky' || class_g ?= 'Notify-osd' || class_g = 'Cairo-clock' || _GTK_FRAME_EXTENTS@";
    shadow = false;
  },
  {
    match = "window_type = 'dock' || window_type = 'desktop'";
    corner-radius = 0;
    blur-background = false;
  }
);
