#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 30
bspc config bottom_padding 0

bspc config initial_polarity first_child
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   "#555555"
bspc config focused_border_color  "#b8bb26"
bspc config active_border_color   "#555555"
bspc config presel_feedback_color "#b8bb26"

bspc config focus_follows_pointer true

bspc rule -a Nuclear-music-player state=tiled layer=normal

~/.config/bspwm/autostart.sh &
