#!/usr/bin/env zsh

DIR_VOID="$HOME/void-packages"
DIR_SRCPKGS="$DIR_VOID/srcpkgs"

pkg="$(ls -1 "$DIR_SRCPKGS" | dmenu -i -p "Src-Packages:")"
[[ -z "$pkg" ]] && exit 0

if xbps-query "$pkg" >/dev/null 2>&1; then
    notify-send "Cancelado" "'$pkg' já está instalado."
    exit 0
fi

if [[ -d "$DIR_SRCPKGS/$pkg" ]]; then
    notify-send "Compilando" "Acompanhe '$pkg' no terminal."
    st -e zsh -c "
        cd '$DIR_VOID' || exit
        print -P '%F{green}[1/3] Atualizando repositório do void-packages (git pull)...%f'
        git pull
        print -P '\n%F{yellow}[2/3] Iniciando compilação (xbps-src)...%f'
        ./xbps-src pkg '$pkg'
        if [ \$? -eq 0 ]; then
            print -P '\n%F{cyan}[3/3] Instalando pacote binário...%f'
            sudo xbps-install --repository hostdir/binpkgs '$pkg'
            notify-send 'Sucesso' 'O pacote $pkg foi instalado.'
        else
            notify-send 'Erro' 'A compilação de $pkg falhou.'
        fi
        print -P '\n%F{red}Pressione [ENTER] para fechar o terminal...%f'
        read
    "
else
    notify-send "Erro" "Pacote '$pkg' não encontrado."
    exit 1
fi
